In [1]:
pip install pandas

Requirement already satisfied: pandas in ./venv/lib/python3.10/site-packages (2.1.0)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.10/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: numpy>=1.22.4 in ./venv/lib/python3.10/site-packages (from pandas) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in ./venv/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip available: 22.2.2 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import Select
from selenium.webdriver.chrome.service import Service

service = Service()
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(service=service, options=options)

In [3]:
# driver = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options)

In [4]:
driver.get('https://knoxschools.munisselfservice.com/employmentopportunities/default.aspx')

In [5]:
driver.find_element(By.XPATH, '//*[@id="ctl00_ctl00_PrimaryPlaceHolder_ContentPlaceHolderMain_RowsPerPageDropDownListTop"]').click()

In [6]:
driver.find_element(By.XPATH, '//*[@id="ctl00_ctl00_PrimaryPlaceHolder_ContentPlaceHolderMain_RowsPerPageDropDownListTop"]/option[6]').click()

In [7]:
all_data = driver.find_elements(By.CLASS_NAME, 'aligntop')

In [8]:
# all_data.text

In [9]:
# for each_block in all_data:
#     print(each_block.text)

In [10]:
for each_job in all_data[:5]:
    each_element = each_job.find_elements(By.TAG_NAME, "p")
    for count, element in enumerate(each_element):
        print(count, element.text)
    print("--")

0 TRANSPORTATION RADIO DISPATCHER TIME CARD
1 Location: TRANSPORTATION
2 Job Family: CLASSIFIED
3 Job Class: TIMECARD
4 Posting Start: 07/03/2023
5 Posting End: 05/24/2024
6 Details: JOB DESCRIPTION
7 APPLY
8
9
--
--
0 ASSISTANT SOFTBALL COACH / EXTRA / FULTON HIGH SCHOOL
1 Location: FULTON HIGH
2 Job Family: CLASSIFIED
3 Job Class: ATH COACH SOFTBALL ASSISTANT
4 Posting Start: 09/27/2022
5 Posting End: 11/29/2023
6 APPLY
7
8
--
--
0 STRENGTH AND CONDITIONING COACH / HARDIN VALLEY ACADEMY
1 Location: HARDIN VALLEY ACADEMY
2 Job Family: CLASSIFIED
3 Job Class: ATHLETIC COACH
4 Posting Start: 07/31/2021
5 Posting End: 11/29/2023
6 APPLY
7
8
--

In [11]:
def extract_key_value_pairs(text):
    # Initialize an empty dictionary to store the key-value pairs
    extracted_data = {}

    # Split the data into lines and iterate through each line
    lines = text.strip().split("\n")
    title_line = lines[0].strip()
    if len(title_line) != 0:
        extracted_data["title"] = title_line
    for line in lines[1:]:
        # Check if the line contains a key-value pair
        if ":" in line:
            key, value = line.split(":", 1)
            extracted_data[key.strip()] = value.strip()
        else:
            # Stop extracting data when we reach the line with "APPLY"
            if line.strip() == "APPLY":
                break

    return extracted_data

all_results = []
for each_job in all_data:
    each_element = each_job.text
    result = extract_key_value_pairs(each_element)
    if result:
        all_results.append(result)
# print(all_results)

In [12]:
import pandas as pd

In [13]:
#  if len(all_data) < 5:
#         print("insufficient data")
#         continue
#     else:

In [14]:
df = pd.DataFrame(all_results)

In [15]:
df.head(10)

,title,Location,Job Family,Job Class,Posting Start,Posting End,Details,MINIMUM SALARY,DAILY RATE RANGE,Salary,HOURLY RATE RANGE,SALARY RANGE
0,TRANSPORTATION RADIO DISPATCHER TIME CARD,TRANSPORTATION,CLASSIFIED,TIMECARD,07/03/2023,05/24/2024,JOB DESCRIPTION,NaN,NaN,NaN,NaN,NaN
1,ASSISTANT SOFTBALL COACH / EXTRA / FULTON HIGH...,FULTON HIGH,CLASSIFIED,ATH COACH SOFTBALL ASSISTANT,09/27/2022,11/29/2023,NaN,NaN,NaN,NaN,NaN,NaN
2,STRENGTH AND CONDITIONING COACH / HARDIN VALLE...,HARDIN VALLEY ACADEMY,CLASSIFIED,ATHLETIC COACH,07/31/2021,11/29/2023,NaN,NaN,NaN,NaN,NaN,NaN
3,TRANSPORTATION BUS ASSISTANT (TIME CARD),TRANSPORTATION,CLASSIFIED,NaN,07/18/2022,10/31/2023,Job Description,NaN,NaN,NaN,NaN,NaN
4,ASSISTANT FOOTBALL COACH / SOUTH DOYLE HIGH SC...,SOUTH DOYLE HIGH,CLASSIFIED,ATH COACH FOOTBALL ASSISTANT,07/21/2022,11/29/2023,NaN,NaN,NaN,NaN,NaN,NaN
5,ASSISTANT WRESTLING COACH / FULTON HIGH SCHOOL,FULTON HIGH,CLASSIFIED,ATH COACH WRESTLING ASSISTANT,07/12/2022,11/29/2023,NaN,NaN,NaN,NaN,NaN,NaN
6,EDUC ASSIST SATL SP 23/24SY,RIDGEDALE ALTERNATIVE,CLASSIFIED,EDUCATIONAL ASSISTANT ALT SPD,07/03/2023,09/30/2023,JOB DESCRIPTION,"$26,439.00",NaN,NaN,NaN,NaN
7,EDUC ASSIST 504 ELEVATE PROGRAM 23/24SY,SYSTEMWIDE,CLASSIFIED,EDUCATIONAL ASSISTANT SPED MS,07/03/2023,09/30/2023,JOB DESCRIPTION,"$22,308.00",NaN,NaN,NaN,NaN
8,"TUTOR LITERACY ES - FULL TIME, PART TIME AVAIL...",AL LOTTS ELEMENTARY,CLASSIFIED,TUTOR LITERACY,06/26/2023,04/30/2024,JOB DESCRIPTION,NaN,$125.00-$125.00,NaN,NaN,NaN
9,"TUTOR LITERACY ES - FULL TIME, PART TIME AVAIL...",ADRIAN BURNETT ELEMENTARY,CLASSIFIED,TUTOR LITERACY,06/26/2023,04/30/2024,JOB DESCRIPTION,NaN,$125.00-$125.00,NaN,NaN,NaN

In [16]:
df.to_csv('jobs_KCS_Sep28.csv')

In [17]:
# df.dropna()
# df = df.reset_index(drop=True)

In [18]:
df.head(10)

,title,Location,Job Family,Job Class,Posting Start,Posting End,Details,MINIMUM SALARY,DAILY RATE RANGE,Salary,HOURLY RATE RANGE,SALARY RANGE
0,TRANSPORTATION RADIO DISPATCHER TIME CARD,TRANSPORTATION,CLASSIFIED,TIMECARD,07/03/2023,05/24/2024,JOB DESCRIPTION,NaN,NaN,NaN,NaN,NaN
1,ASSISTANT SOFTBALL COACH / EXTRA / FULTON HIGH...,FULTON HIGH,CLASSIFIED,ATH COACH SOFTBALL ASSISTANT,09/27/2022,11/29/2023,NaN,NaN,NaN,NaN,NaN,NaN
2,STRENGTH AND CONDITIONING COACH / HARDIN VALLE...,HARDIN VALLEY ACADEMY,CLASSIFIED,ATHLETIC COACH,07/31/2021,11/29/2023,NaN,NaN,NaN,NaN,NaN,NaN
3,TRANSPORTATION BUS ASSISTANT (TIME CARD),TRANSPORTATION,CLASSIFIED,NaN,07/18/2022,10/31/2023,Job Description,NaN,NaN,NaN,NaN,NaN
4,ASSISTANT FOOTBALL COACH / SOUTH DOYLE HIGH SC...,SOUTH DOYLE HIGH,CLASSIFIED,ATH COACH FOOTBALL ASSISTANT,07/21/2022,11/29/2023,NaN,NaN,NaN,NaN,NaN,NaN
5,ASSISTANT WRESTLING COACH / FULTON HIGH SCHOOL,FULTON HIGH,CLASSIFIED,ATH COACH WRESTLING ASSISTANT,07/12/2022,11/29/2023,NaN,NaN,NaN,NaN,NaN,NaN
6,EDUC ASSIST SATL SP 23/24SY,RIDGEDALE ALTERNATIVE,CLASSIFIED,EDUCATIONAL ASSISTANT ALT SPD,07/03/2023,09/30/2023,JOB DESCRIPTION,"$26,439.00",NaN,NaN,NaN,NaN
7,EDUC ASSIST 504 ELEVATE PROGRAM 23/24SY,SYSTEMWIDE,CLASSIFIED,EDUCATIONAL ASSISTANT SPED MS,07/03/2023,09/30/2023,JOB DESCRIPTION,"$22,308.00",NaN,NaN,NaN,NaN
8,"TUTOR LITERACY ES - FULL TIME, PART TIME AVAIL...",AL LOTTS ELEMENTARY,CLASSIFIED,TUTOR LITERACY,06/26/2023,04/30/2024,JOB DESCRIPTION,NaN,$125.00-$125.00,NaN,NaN,NaN
9,"TUTOR LITERACY ES - FULL TIME, PART TIME AVAIL...",ADRIAN BURNETT ELEMENTARY,CLASSIFIED,TUTOR LITERACY,06/26/2023,04/30/2024,JOB DESCRIPTION,NaN,$125.00-$125.00,NaN,NaN,NaN